version: '3.8'

services:

  sb-frontend:
    build:
      context: ./frontend
    image: showball-frontend
    container_name: sb-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    networks:
      - sb-network
    depends_on:
      - sb-backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  sb-backend:
    build:
      context: ./backend
    image: showball-backend
    container_name: sb-backend
    depends_on:
      - sb-mongo
    volumes:
      - ./backend/:/app
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:8080"
    networks:
      - sb-network
    env_file:
      - ./backend/.env
    command: bash -c "poetry run uvicorn --host 0.0.0.0 app.main:app --port 8080 --reload"

  sb-mongo:
    image: mongo:5.0.17
    container_name: sb-mongo
    ports:
      - 27017:27017
    networks:
      - sb-network
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

networks:
  sb-network:
