services:
  backend:
    build:
      context: ./backend
    image: showball-backend
    depends_on:
      - db
    volumes:
      - ./backend/src/:/app/src/
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:8080"
    env_file:
      - ./.env
  db:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  mongo-data:
