version: '3.8'

services:

  sb-backend:
    build:
      context: ./backend
    image: showball-backend
    container_name: sb-backend
    depends_on:
      - sb-mongo
    volumes:
      - ./backend/src/:/app/src/
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:8080"
    networks:
      - sb-network
    environment:
      PORT: "8080"
      APP_SECRET: "secret-key"
      DATABASE_NAME: "showball"
      DATABASE_USER: "admin"
      DATABASE_PASS: "admin"
      DATABASE_URI: "mongodb://sb-mongo:27017"

  sb-mongo:
    image: mongo:6.0
    container_name: sb-mongo
    ports:
      - 27017:27017
    networks:
      - sb-network
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

networks:
  sb-network:
