services:
  frontend:
    build:
      context: ./frontend
    image: showball-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_BACKEND_URI: ${BACKEND_URI}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: showball-backend
    depends_on:
      - db
    volumes:
      - ./backend/src/:/app/src/
      - ./backend/uploads/:/app/uploads/
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    restart: unless-stopped

  db:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped

volumes:
  mongo-data:
