db = db.getSiblingDB("showball");

db.createCollection("tokens");

db.tokens.insertMany([
  {
    textId: "slimak",
    name: "Slimák",
    description: "",
    imageSrc: "uploads/tokens/slimak.png",
    levels: [
      {
        coins: 1,
        points: 1,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 2,
        points: 2,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 3,
        points: 3,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "krtek",
    name: "Krtek",
    description: "",
    imageSrc: "uploads/tokens/krtek.png",
    levels: [
      {
        coins: 1,
        points: 1,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 2,
        points: 2,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 3,
        points: 3,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "mozek",
    name: "Mozek",
    description: "",
    imageSrc: "uploads/tokens/mozek.png",
    levels: [
      {
        coins: 2,
        points: 2,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 3,
        points: 3,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "laso",
    name: "Laso",
    description: "",
    imageSrc: "uploads/tokens/laso.png",
    levels: [
      {
        coins: 3,
        points: 3,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 7,
        points: 7,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "slon",
    name: "Slon",
    description: "",
    imageSrc: "uploads/tokens/slon.png",
    levels: [
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 7,
        points: 7,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 8,
        points: 8,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "netopyr",
    name: "Netopýr",
    description: "",
    imageSrc: "uploads/tokens/netopyr.png",
    levels: [
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 7,
        points: 7,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 8,
        points: 8,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "kozel",
    name: "Kozel",
    description: "",
    imageSrc: "uploads/tokens/kozel.png",
    levels: [
      {
        coins: 3,
        points: 3,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 7,
        points: 7,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "kanon",
    name: "Kanón",
    description: "",
    imageSrc: "uploads/tokens/kanon.png",
    levels: [
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 7,
        points: 7,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 8,
        points: 8,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 9,
        points: 9,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 10,
        points: 10,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "moucha",
    name: "Moucha",
    description: "",
    imageSrc: "uploads/tokens/moucha.png",
    levels: [
      {
        coins: 3,
        points: 3,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 7,
        points: 7,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
  {
    textId: "hodinky",
    name: "Hodinky",
    description: "",
    imageSrc: "uploads/tokens/hodinky.png",
    levels: [
      {
        coins: 3,
        points: 3,
        exps: 0,
        nextLevelCost: 10,
      },
      {
        coins: 4,
        points: 4,
        exps: 0,
        nextLevelCost: 15,
      },
      {
        coins: 5,
        points: 5,
        exps: 0,
        nextLevelCost: 25,
      },
      {
        coins: 6,
        points: 6,
        exps: 0,
        nextLevelCost: 40,
      },
      {
        coins: 7,
        points: 7,
        exps: 0,
        nextLevelCost: 60,
      },
    ],
    maxLevel: 5,
    state: true,
  },
]);
